apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ogbah1o5v-python 
  janus-idp.io/tekton: ogbah1o5v-python
  backstage.io/kubernetes-id: ogbah1o5v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ogbah1o5v-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml